name: CI
on:
  push:
    branches:
      - dev
      - "feat/**"

# 1. 테스트
# 2. PR
env:
  NEXT_PUBLIC_API_URL: ${{secrets.NEXT_PUBLIC_API_URL}}

jobs:
  run-test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - name: Downloads Codes
        uses: actions/checkout@v4

      - name: Install Deps
        run: npm install

      - name: Run Test
        run: npm run test

      - name: Run Build
        run: npm run build
