# main 브랜치에 push를 하면
# 테스트 -> 빌드드

name: Run Test And Build
# push, workflow_dispatch(manually trigger)
# 이벤트 대해서만 트리거 됨
on: [push, workflow_dispatch]
jobs:
  # 1. 테스트
  test:
    runs-on: ubuntu-latest
    steps:
      # 코드를 가져옴.
      - name: Get Codes
        uses: actions/checkout@v4

      # 의존성 파일들 설치
      - name: Install Dependencies
        run: npm install
  # 2. 빌드
